# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x0cvideoservice\"\x07\n\x05\x45mpty\"\x19\n\tImageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"$\n\x0cOdometryData\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x32\x91\x01\n\x0cVideoService\x12=\n\x0bStreamVideo\x12\x13.videoservice.Empty\x1a\x17.videoservice.ImageData0\x01\x12\x42\n\x0fGetOdometryData\x12\x13.videoservice.Empty\x1a\x1a.videoservice.OdometryDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=37
  _globals['_EMPTY']._serialized_end=44
  _globals['_IMAGEDATA']._serialized_start=46
  _globals['_IMAGEDATA']._serialized_end=71
  _globals['_ODOMETRYDATA']._serialized_start=73
  _globals['_ODOMETRYDATA']._serialized_end=109
  _globals['_VIDEOSERVICE']._serialized_start=112
  _globals['_VIDEOSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
